### PR TITLE
Fix some DBZ movies

### PR DESCRIPTION
**Pull request by mweber03**
Fixed some DBZ movies
Ran `update.sh` (somewhat of an accident my now my changes are mixed in)

### CODE REVIEW

**Comment by mweber03** [comment]
@slohj @sixtenbe please merge

**Comment by sixtenbe** [comment]
I Manually added your changes in a [commit](https://github.com/ScudLee/anime-lists/commit/12658cc938b56ee1035078725f09332b571ba584) to avoid animetitles update with mapping update. 

Check that they're good and for some reason I saw that AniDB1071 Dragon Ball Z: Fukkatsu no Fusion!! Gokuu to Vegeta doesn't appear to have any movie parts so I removed those mappings as well. Open an Issue or a new Pull request if I missed something.

**Comment by purposelycryptic** [comment]
...You're too fast for me, was just in the middle of doing the same thing...

**Comment by purposelycryptic** [comment]
Not sure the offsets are really necessary for [a905](https://anidb.net/a905), [a906](https://anidb.net/a906), [a1044](https://anidb.net/a1044), [a1069](https://anidb.net/a1069), [a1070](https://anidb.net/a1070) and [a1071](https://anidb.net/a1071), as per the readme: 

> episodeoffset - Number to add to each regular AniDb.net episode number to get the corresponding  theTVDB.com episode number in the defaulttvdbseason. Not necessary if the episode numbers match up exactly. **For special episodes and more complex situations the mapping-list is used**

If there is already a need for the complexity of a mapping list for the rest of the episodes, additionally adding an offset for one episode seems to mainly make things more complicated.

**Comment by sixtenbe** [comment]
The solutions are equivalent, so I just mimicked mweber03 in how he did the mapping. 

As for a1071, there is  only one episode on AniDB no movie parts, so a offset makes the most sense in that case. Considering the previous mapping I feel like movie parts should have existed, but maybe they only were generic files and I'm not sure if there is any creq history for episode deletion.

**Comment by purposelycryptic** [comment]
You're completely correct RE: a1071 - I was in the middle of writing up a response addressing the changes in the PR when I saw that it had already been handled. and my response ended up being copy-pasted together from that, and a1071 accidentally got included.

A lot of these splits are from back when groups were releasing movies in parts that would fit on a single CD-R; that trend was dying off by the time that movie made it west (2006), so I'm guessing there simply was no release group that made one for it.

**Pull request closed without merging**
