### PR TITLE
LOTS of additions, some fixes

### PR DESCRIPTION
**Pull request by purposelycryptic**
@slohj 
This is essentially Pull Request #281, but without whatever it was that made it unmergeable. It has every series, movie, OVA, hentai, etc from Summer 2019, plus lots of older additions from Spring and Winter 2019, and from Fall 2018, as well as a whole bunch of other additions. There are also a few for Fall 2019+.

I rebased this branch to the current master, then added the updated `anime-list-master.xml`, so it is exactly the same, content-wise, but I guess GitHub didn't like the 5 million commits slowly added to the other branch being in a single pull request ¯\_(ツ)_/¯.

Whatever the reason, it seems it is no longer present here, so I'll close that Pull Request, and if you could accept this one, it would really make my day/week/month, since a lot of these additions have been just sitting here for quite a while now.

### CODE REVIEW

**Comment by slohj** [comment]
I went ahead and merged this but my understanding is that tvdbid's and indbid's are not necessary or even wanted for regular series, only movies or things that will not ever be added to tvdb.

That was a lot of work!

**Comment by purposelycryptic** [comment]
Awesome 👍😁

Yeah, I started putting mappings up as issues earlier in the year, and they kept piling up, so I ended up closing those and putting them all in a Pull Request, then the changes kept piling up there, until the commits became convoluted enough that GitHub couldn't find a way to merge them.

In the end, I looked up how to rebase my mostly untouched master branch onto your latest commit, then swapped in the anime-list-master.xml (which I had already gone through to manually eliminate any conflicts with your latest commit to the master), and, finally, no more conflicts :-)

It's been a while, so I'm not fully 100% certain, but I believe that also included all pending issues that were in the issue tracker. 

It also included the changes from the pending PR by @atraholt for the various Nanoha franchise entries, as I added those to my branch a while back (had to slightly modify the Specials redirect to 0, changing it to 99 instead, as someone had added an episode 0 to TheTVDB since the pull request was created), so many thanks to them as well!

RE: TMDB and IMDB ID's, I know the Readme mentions them as an either/or optional mapping for series, although I'm not exactly sure for the reasoning behind that; probably because it could cause issues if you add them to sequel series/second+ seasons, since the list only maps to the overall series entry for those providers, so you could end up with multiple AniDB IDs mapped to the same TMDB/IMDB entry. Going by that assumption, I only added them to the first series in a franchise, so they wouldn't generate conflicts.

I always try to add TMDB mappings to series (outside of the exceptions just mentioned), as they frequently have posters and backdrops that aren't on TheTVDB, giving a wider range of options. 

As for IMDB mappings, it's true there currently isn't much use for them, since they have so little series metadata, but that could always change in the future; I'll admit, though, that I mostly added those because the ID was just sitting there on a series' TheTVDB page, and it just felt wrong leaving the field blank when the data was right there. I may be slightly OCD... :P

Anyway, thanks again! After all this time, it feels great to see all those mappings actually be usable by people other than just myself. 

Ironically, the Summer 2019 mappings are probably now more complete than the Winter or Spring 2019 ones; I know I added quite a few of those series, but I did so whenever I noticed they were missing, rather than going through the whole list one at a time, so there are probably still a number missing - I'll see if I can do a full check on them sometime soon.

**Comment by sixtenbe** [comment]
I just want to add that there is a very simple reason that the readme treats imdb and tmdb links as an exclusive or. It's quite simply that the tmdb entry can be obtained by searching by imdbid on tmdb so only one entry should be added with preference on imdb as long as it actually matches the anidb entry. 

If the tmdb page isn't linked with the imdbid you should go on tmdb and edit the page to add the imdbid, which any user can add there.

So for any future entries don't bother adding both since tmdb automatically is linked with the imdbid, with the responsibility of this being upon app developers to check and I expect apps might end up pulling tmdb data twice as the they check the tmdbid and then once again do the same lookup using imdbid, creating duplicates of cover art or other things.

It's just best to follow the definitions of the readme, since app developers might not write their apps to correctly handle cases where you deviate from the readme. There are also features which aren't fully described in the readme, such as how to link non S-specials like t-specials and op-ed specials.

Other than this I'd say you did some good work.

**Comment by purposelycryptic** [comment]
Thanks:)

I just always add the TMDB because I use HAMA for my Plex Server metadata, and I know that, as a high-volume metadata agent, it just pulls data from either AniDB/TheTVDB unless there is an explicit ID defined for IMDB, as looking  for IDs from other sites inside the data it pulls, or trying to pull data using an ID string from another site would add a good bit to the processing time. TMDB tends to also both have entries for a lot of movies/series IMDB doesn't, and usually has some posters/backdrops TheTVDB doesn't. 

But I'll just skip the IMDB ID in the future, then. There are, after all, far more series/movies not on IMDB than on TMDB, and not much useful metadata on IMDB itself even when it does have an entry. And most of the IMDB IDs I added came from TheTVDB entry anyway (after checking it was still up-to-date).

I do agree the readme could probably use some expansion in some areas, going into a little more detail, giving examples, etc - in a perfect world, that would go into a wiki, but I don't think we have anyone with the knowledge, desire, technical writing skill, free time and access privileges to create a detailed, useful one.

I had no clue that mapping C, T and O episodes was even supported in any way (Nor, I believe, do many of the devs whose projects make use of the anime-lists); it's not a big deal for C and T episodes, as none of the sites mapped to support entries for OP/EDs or Trailers (Though contributors occasionally try to sneak them in), but some O episodes _are_ actually on TheTVDB. Not that there are that many of those to begin with, but being able to map those for overly complex series, like the Monogatari franchise, would definitely be beneficial.

**Pull request merged**
