### PR TITLE
Hanamonogatari: Suruga Devil

### PR DESCRIPTION
**Pull request by bjggi**
Mapping

### CODE REVIEW

**Comment by ScudLee** [comment]
Need to map episode 1 somewhere too, otherwise it'll get the plot from "Episode 5.5 (Recap)" of Bakemonogatari.

I'd suggest either 1-10 or 1-10+11 (sadly the scraper can only join two episodes together).

**Comment by bjggi** [comment]
Ah ofc, i would just do 1-10. 

Here is also the Mapping for Tsukimonogatari: (not sure about defaulttvdbseason?)

<anime anidbid="10891" tvdbid="102261" defaulttvdbseason="0" tmdbid="" imdbid="tt4213580">
<name>Tsukimonogatari: Yotsugi Doll</name>
<mapping-list>
<mapping anidbseason="1" tvdbseason="0">;1-15;2-15;3-16;4-17;5-18;</mapping>
</mapping-list>
</anime>

Can you fix both manually? Im not that sure how to revert/change my pull request.  :)

Best Regards 
Vaneska

**Comment by bjggi** [comment]
Hope i did this right :+1:

**Comment by ScudLee** [comment]
I think I manually added these changes a while ago.  

You still needed to squash the revert commit down to keep the history clean (but I felt bad about always asking you to jump through so many hoops.) 

But still, thank you (as always).

**Pull request closed without merging**
