### PR TITLE
Added some movies tmdb and imdb.

### PR DESCRIPTION
**Pull request by bernimoses**

### CODE REVIEW

**Comment by ScudLee** [comment]
I manually added the Fairy Tail imdb id.  Only one id is needed (with preference to imdb), so there was no need to add the tmdb ids.  Thanks.

**Comment by bernimoses** [comment]
What about 'Gekijouban Shakugan no Shana'?

**Comment by ScudLee** [comment]
Like I said only one id is needed.  

The Shana movie already had an imdb id, so no further action was required.

**Comment by bernimoses** [comment]
Oh sry, i thought it was referred to Fairy Tail.

**Pull request closed without merging**
