### PR TITLE
A decent update

### PR DESCRIPTION
**Pull request by sixtenbe**
This is your your latest merged into my interim branch, which contains edits from the following issues:
https://github.com/ScudLee/anime-lists/issues/81
https://github.com/ScudLee/anime-lists/issues/82
https://github.com/ScudLee/anime-lists/issues/83

and Edits to add the following series:
Nanbaka (2017)
Fate Grand Order
Youjo Senki
Urara Meirochou
Shouwa Genroku Rakugo Shinjuu: Sukeroku Futatabi Hen
Seiren
Minami Kamakura Koukou Joshi Jitensha Bu
Masamune-kun no Revenge
Kubikiri Cycle Aoiro Savant to Zaregoto Tsukai
Koro-sensei Quest! (2016)
Koro-sensei Quest!
Demi-chan wa Kataritai
Ao no Exorcist: Kyoto Fujouou Hen
Akiba's Trip The Animation
Spirit Pact
Fuuka
Kizumonogatari 3 IMDB ids
Hakuouki: Otogisoushi
Bakuon!! OAD
Biohazard: Vendetta
Kuroshitsuji: Book of the Atlantic
Nyanko Days
Eldlive
Tales of Zestiria the Cross (2017)
Idol Jihen
Gabriel DropOut
Chiruran: Nibun no Ichi
Yowamushi Pedal: New Generation
Onihei
Onihei: Sono Otoko, Hasegawa Heizou
Hand Shakers
Koutetsujou no Kabaneri Soushuuhen
6HP
Kaijuu Girls: Ultra Kaijuu Gijinka Keikaku
Danganronpa 3: The End of Kibougamine Gakuen - Zetsubou Hen (this is a mess on tvdb)
Hagane Orchestra
Zegapain ADP

### CODE REVIEW

**Comment by sixtenbe** [comment]
lol forgot that I managed to change the gitignore files when messing about, to avoid committing any changes to the batch files I made

**Comment by ScudLee** [comment]
Adding the batch files to .gitignore is definitely not good.  I deliberately exposed them so that other people could use them.  

You should use ```git update-index --assume-unchanged <file-name>``` to make local changes to a tracked file without risking committing them.

**Comment by sixtenbe** [comment]
Restored the gitignore file to the previous state and ran that command, thx.

**Comment by ScudLee** [comment]
One thing I should say, before I pull all this, is that you shouldn't, as a rule, merge changes in _from_ upstream in a pull request when the ultimate intention is to merge back _into_ the upstream.  If there is a conflict (or new things to add) you should rebase instead, and force push the changes to the PR branch.

That said, the main reason for that is because otherwise it makes the history messy, which isn't really that big of a deal in this case.  Plus at this point it's more important to get these fixes in than waste extra time making everything look pretty.

However, if I do give you write access, there may be instances where you'll have to rebase locally (to avoid edit conflicts) if you're working directly on the master branch.  Never resolve the conflict by merging, or by force pushing and rewriting the history of the upstream (i.e. my) master branch.

**Comment by sixtenbe** [comment]
Ok, good to know that. I didn't know about the rebase feature and reading the documentation about it, I see why it would fit a lot better for this type of action.

Haven't used git that much as most of my programs happened to suit best with an on disk hg repo and I never needed any branching and no seriously conflicting merges, at least not beyond forgetting to pull the latest version before changing some code.

**Pull request merged**
