### PR TITLE
Rewrite generate-lists.bat as platform-independent Groovy script

### PR DESCRIPTION
**Pull request by rednoah**

### CODE REVIEW

**Comment by ScudLee** [comment]
I trust you've tested the script and confirmed the outputs are identical?

Can you make an edit to anime-list-master.xml, use the script and commit the changes for proof?

Here's an example if you need an edit to make:
```
  <anime anidbid="9337" tvdbid="72347" defaulttvdbseason="0" episodeoffset="20" tmdbid="258156" imdbid="">
    <name>Macross FB7: Ore no Uta o Kike!</name>
  </anime>
```

**Comment by rednoah** [comment]
Well, almost... The xml declaration is slightly different and it doesn't preserve comments. The XML content is exactly the same though.

**Comment by rednoah** [comment]
Made it more similar: `./generate-lists.groovy && git diff` now yields the following:
```
diff --git a/anime-list-todo.xml b/anime-list-todo.xml
index 111cde7..87ea269 100644
--- a/anime-list-todo.xml
+++ b/anime-list-todo.xml
@@ -1,24 +1,5 @@
 <?xml version="1.0" encoding="utf-8"?>
 <anime-list>
-  <!--TEMPLATE
-  <anime anidbid="" tvdbid="" defaulttvdbseason="" tmdbid="" imdbid="">
-    <name></name>
-    <mapping-list>
-      <mapping anidbseason="" tvdbseason=""></mapping>
-    </mapping-list>
-    <before></before>
-    <supplemental-info replace="">
-      <studio></studio>
-      <genre></genre>
-      <actor></actor>
-      <director></director>
-      <credits></credits>
-      <thumb aspect=""></thumb>
-      <fanart>
-        <thumb dim="" colors="" preview=""></thumb>
-      </fanart>
-    </supplemental-info>
-  </anime> -->
   <anime anidbid="1078" tvdbid="" defaulttvdbseason="" episodeoffset="" tmdbid="" imdbid="">
     <name>Doraemon (1979)</name>
   </anime>
@@ -3782,4 +3763,3 @@
     <name>Handa-kun</name>
   </anime>
 </anime-list>
-<!--1254 titles remaining-->
```

`xs:comment` doesn't produce any output with the Java XML API. Wouldn't know what to do about that.

**Comment by ScudLee** [comment]
Sorry for the delay in replying.

After consideration,  I'm not that bothered by the lack of comments in anime-list-todo.xml.  The file is mostly ornamental anyway, so if the comments disappear in one commit and come back in another, it's no big deal.  So this is good to go in.

I do need you to update the README.md to explain usage/requirements first, though (since I don't fully know what they are).
Doesn't have to be pretty - I can always fix up formatting if necessary.

**Comment by rednoah** [comment]
Added some docs.

**Comment by ScudLee** [comment]
Finally!  Sorry for taking so long to push a button.

**Pull request merged**
