### PR TITLE
Additional Fall 2019 Updates

### PR DESCRIPTION
**Pull request by sven-7**

### CODE REVIEW

**Comment by slohj** [comment]
I've got your tree in my working repo now so quick merges are easy.  Is there a reason you don't generate the lists for testing?

**Comment by sven-7** [comment]
Awesome - thanks! 

I more stopped myself lack of know-how and from the readme saying the below, but I assume as long as I run `generate-list.bat` or `generate-list.sh` it should generate properly.

> Do not edit any other lists as they are automatically generated, either use generate-lists.bat or leave them to be updated after the Pull Request has been pulled.

**Comment by slohj** [comment]
Do the pull request so I can get the email alert.
I'll be updating the titles again soon, so keep you master branch up to date before the pull request.  I always fetch all the branches I track (now including yours) before I do any of my changes.
I'm probably going to watch 4 or 5 shows this season and you've already add 3 of the posibles.  There is just not anything that interesting to me.  I'm concentrating on old anime this season.
Thanks for the work.

**Comment by sven-7** [comment]
Will do. Works for me. I'll keep it up to date and monitor this.

Yeah - I agree. I'm just adding things as I see them, but definitely adding more then I'll end up watching.

**Pull request merged**
