### PR TITLE
Fix Beyblade Burst mapping

### PR DESCRIPTION
**Pull request by dsonck92**
Beyblade Burst (and other seasons) are part of a new TV Show entry on TheTVDB and not a continuation of the original 2001 series Beyblade.

### CODE REVIEW

**Comment by sven-7** [comment]
Can you do a PR in https://github.com/Anime-Lists/anime-lists for this?

**Comment by dsonck92** [comment]
I just did, I was looking at the repo network and realized this around the same time

**Comment by sven-7** [comment]
Committed and done!

**Comment by dsonck92** [comment]
Perfect, I also just verified that HAMA also uses the Anime-Lists version, so that's good too. Now I can finally correctly scan them.

**Pull request closed without merging**
