### PR TITLE
Additions - Fall 2019

### PR DESCRIPTION
**Pull request by purposelycryptic**
This should largely finish up the mappings for the Fall 2019 season.

Note that I am pretty much basing this off of the [AniDB Season Chart](https://anidb.net/anime/season/?do.filter=1) as it was on **2019/10/03**. 

I did a quick comparison between the **animetitles.xml** from then and the one currently used by the anime-lists, and included the newest series added at the end, but I know there are at least a handful of entries on AniDB that were not yet included in the latest **animetitles.xml** on GH (One 18+ OVA, and an unknown number of regular entries).

PS: See commit comment for list of entries mapped, alongside their AniDB-ID.

### CODE REVIEW

**Comment by purposelycryptic** [comment]
If anyone could merge this PR (@slohj?), that would be awesome and you would be doing me a huge favor, as the Fall season is still full of holes as is. 

<(_ _)>

**Comment by sixtenbe** [comment]
```xml
<anime anidbid="14239" tvdbid="353666" defaulttvdbseason="0" episodeoffset="5" tmdbid="637202, 637462" imdbid="">
    <name>Gekijouban Fate/Grand Order: Shinsei Entaku Ryouiki Camelot</name>
```
The delimiter for tmdbids and imdbids is comma "," not ", ", I'm not sure hamana is bothering to strip the whitespace.

Also unless hamana has changed, I'd strongly recommend against adding tmdbids for tv series, since hamana assumes a tmdbid is for movies and as such any data from such a lookup will pull posters from a random movie with the same id.

Fix the delimiter and I'll merge it.

**Comment by purposelycryptic** [comment]
Removed the white-space between the IDs.

RE:

> Also unless hamana has changed, I'd strongly recommend against adding tmdbids for tv series, since hamana assumes a tmdbid is for movies and as such any data from such a lookup will pull posters from a random movie with the same id.

I've never noticed that happening in the time I've used HAMA, and was unable to duplicate it just now, but it was admittedly a rather limited test, with a sample size of only 2 series. 

If that is the case, though, it would be a real shame, given TMDB frequently has better posters and backdrops (and almost always some TVDB does not), and, AFAIK, HAMA doesn't make use of the TMDB API's `/find` function to locate entries using their TVDB or IMDB ID.

The example you posted was for actual movies, however, TVDB simply categorizes them as specials - I continue to be quite severely ill, so I largely sped through his, and only did TMDB lookups for entries for which no IMDB entry existed (they tend to be fairly spotty on anime), which tend to be movies and OVAs, both of which TMDB classifies as movies.

Anyway, if you could run a title update post-merge, that would be great, as the current animetitles.xml is over 2 weeks old already, and there have been additions since. Thanks!

**Comment by sixtenbe** [comment]
Looking at the search strings at the top of the "TheMovieDb.py" file from hama you can only see these two lookups for tmdb entries
```python
TMDB_MOVIE_SEARCH_BY_TMDBID = 'http://api.tmdb.org/3/movie/%s?api_key=7f4a0bd0bd3315bb832e17feda70b5cd&append_to_response=releases,credits,trailers,external_ids&language=en'  #Work with IMDbid
TMDB_SERIE_SEARCH_BY_TVDBID = "http://api.TheMovieDb.org/3/find/%s?api_key=7f4a0bd0bd3315bb832e17feda70b5cd&external_source=tvdb_id&append_to_response=releases,credits,trailers,external_ids&language=en"
```
You can see that the search by TMBDBID uses /movie/ in it's lookup and the note at the end that it can use imdbid.

It's some time since I did complete check but with the following entry I can see a random poster from some random [movie](https://www.themoviedb.org/movie/83454) in plex instead of the [tv series](https://www.themoviedb.org/tv/83454)
```xml
<anime anidbid="14392" tvdbid="354636" defaulttvdbseason="1" episodeoffset="" tmdbid="83454" imdbid="tt9314454">
    <name>Kouya no Kotobuki Hikoutai</name>
```

**Pull request merged**
