### PR TITLE
Whole bunch of additions, and some corrections

### PR DESCRIPTION
**Pull request by purposelycryptic**
For reasons I can't seem to figure out, I keep getting the **Can’t automatically merge** message, even after manually downloading the base master and reconstructing all the additions/edits - I'm beginning to think VS is just trying to torture me.

Anyway, as per the title, this includes a whole bunch of additions along with a couple corrections (a few instances of TheTVDB changing stuff around, a missing semi-colon in the mappings for one of the Attack on Titan series, that kind of thing).

Sorry for the messy commit history, the majority of them actually contain no changes, as VS was simply being uncooperative, and not properly showing changes after commits, among other irritating behavior.

### CODE REVIEW

**Comment by purposelycryptic** [comment]
If someone could approve this, or at least tell me what I need to do to get it approved and merged, that would be great. I use HAMA, which uses this for its mapping, and no matter how many times I fix things in my local file, it keeps pulling from here periodically, reverting all the fixes and mappings again, messing up metadata.

For example, just a few minutes ago, Trakt scrobbled episodes from the Shingeki no Kyojin OAD as episodes of the first Shingeki no Kyojin, because this list has the mapping as
```
  <anime anidbid="9826" tvdbid="267440" defaulttvdbseason="0" episodeoffset="" tmdbid="" imdbid="">
    <name>Shingeki no Kyojin OAD</name>
    <mapping-list>
      <mapping anidbseason="1" tvdbseason="0">;1-2;2-12;3-13;4-16;5-17;6-20;7-21;8-22</mapping>
    </mapping-list>
  </anime>
```
when it should be:
```
  <anime anidbid="9826" tvdbid="267440" defaulttvdbseason="0" episodeoffset="" tmdbid="" imdbid="">
    <name>Shingeki no Kyojin OAD</name>
    <mapping-list>
      <mapping anidbseason="1" tvdbseason="0">;1-2;2-12;3-13;4-16;5-17;6-20;7-21;8-22;</mapping>
    </mapping-list>
  </anime>
```

That Semi-colon really makes a big difference.

There's also the fact that these additions and fixes have just been piling up for over a month - I put them up as issues initially, then consolidated them into a pull request after receiving zero feedback or signs of life for some time, then eventually got frustrated and closed my pull request because it felt like talking to a wall (except less responsive), then finally made another pull request because just because I'm getting annoyed, shouldn't mean everyone else who uses these lists should have to suffer.

...That was a week ago.

Now, I realize we are all busy people with busy lives here, but I've been seriously ill for the past few months with what may or may not be lung cancer (I should finally get an answer in the next few days), to the point that I've barely been able to get out of bed, and I still managed to throw god-knows how many hours at this, so looking at a pull request (I can't even see what the conflicts are, and rebased the whole thing hoping it would clear that up, but no dice) doesn't seem like too much to ask.

A lot of these fixes/additions are for Winter/Spring 2019, and we're only a few weeks away from the Summer 2019 series starting. That's not a good state progress-wise, and the near total absence of signs of life have pretty much sapped my enthusiasm to keep working on this when it may never see the light of day.

So, @sixtenbe , @slohj , @elvishp2006 , @NextFire , @KurtzPT , sorry to bother you all, I know you don't know me and probably have no specific reason to care, but, as the only people who have made commits in the past three months, I figure you are also the only people with both the necessary Write access and the potential interest in actually using it to keep this thing up-to-date. So, uhm, help me Obi-Wan Kenobi, you're my only hope!

Sorry if I sound grumpy, but I feel really, really crappy, and have spent most of the past months with my head spinning, staring at walls and coughing up things that should really stay inside the body. Plus, I'm a little stressed about the possibility of my doctor potentially calling me at any moment to tell me I'm going to die horribly. Thanks for your time.

**Comment by NextFire** [comment]
Hello, I just finished reading your message. I would first like to express my compassion for your illness, having just seen Kimi no Suizou no Tabetai (I want to eat your pancreas) yesterday makes me even more understanding.
Also I would like to thank you for the time spent on this project, however I don't have any writing access on this repository (my pulls were not merged by myself).

In any case, it seems that I cannot help you very much, but I hope that what you have done is not for nothing and I wish you much courage in your fight against cancer.

**Comment by KurtzPT** [comment]
Same as @NextFire, I also don't have write access and I even tried one time contacting one of the persons who actually have write access (I think it was @slohj), so I could maybe get write access and update this since the development of this is pretty stale, but I had zero responses.

All my PR were actually merged into main branch more than one month after I created them, so don't really expect them to read/do anything with your PR anytime soon. It's unfortunately since like yourself, I also use Hama but I gave up on updating this and I started using the override xml that Hama has for these fixes.

**Comment by purposelycryptic** [comment]
I really appreciate hearing back from you two, @NextFire, @KurtzPT, and I seriously apologize for not writing back until now. 

`＿|￣|○  -->  _/＼○_`

Being sick has become somewhat of a full-time job for me lately, and the past couple weeks have been especially rough, so I ended up spending 90% of my time in a sort of zombie state; I've finally been a bit more clear-headed these past few days, and have been trying to catch up with everything I just kind of ended up dropping and leaving where it fell when the bad days started (including some seriously spoiled bananas - I definitely learned my lesson about keeping perishables when you can't really rely on being in any state to bother with them day-to-day 😋).

Anyway, thanks for the kind words, and it's nice just knowing I'm not the only one bothered by the current state of the project.

Like @KurtzPT, I had also been updating locally, except that I had been using the Master list, rather than HAMA's override list, which made converting my additions/changes into a pull request much easier, since they were already part of the file needed, and I simply had to run the script to update the other lists from there.

Since the Summer season is just about here, assuming my condition doesn't suddenly crash again, I'm thinking of just doing the necessary additions on my fork, and giving write access to anyone who wants to contribute. My health may not make me the ideal person to maintain such a repo (and if anyone else who has worked on the project longer wants to do it, I'll gladly step aside), but I feel like someone needs to do it, otherwise projects like HAMA will suffer serious issues next season.

While only briefly (and contributing very little), I did try to get involved with HAMAs development last year, before EndOfLine369 stepped up, and, being far more experienced than myself, started a whirlwind of new development that left little need for me there (the only feature I still want to add to the main branch is letting users choose between AniDB's weighted and average scores, which I've been manually adding to new versions of HAMA in my server as I hate the weighted scores, and have ever since they were introduced). Anyway, I'm noticing I'm feverish and rambling again, but the point I wanted to make was that if enough people willing to work on the AnimeLists can be convinced to move over to work on a fork that actually has folks with proper access actively doing admin-y things like checking and adding stuff from the issues and processing pull requests, I'm sure ZeroQI (HAMAs creator) would be happy to switch over to that repo for pulling lists, and we might be able to get things running again, though I'm not sure what the situation is like on the Kodi end, since I've never really used it. And if things here end up reviving, it would be a simple matter to move the progress generated in the meantime back over. 

I'm starting to feel like I sound like I'm advocating some sort of coup d'etat, but I really just want to make sure this project survives in some form, since it is an incredibly useful resource, and having it die a slow death like this would be a major loss to the anime community.

**Comment by slohj** [comment]
I'm posting this here because I don't know where else I should put it.

First of all how I see myself in respect to this repo.

I still don't know why I was given write access.  I don't actually use this
repo for kodi.  I use local copies served from my LAN's webserver.  I do not
consider my self to be one of the maintainers of this repo, but I have in the
past and will continue to add my own edits that I have tested.

Real life generally prevents me from paying very much time on this outside of
the shows that I'm actually adding to my own library.

That said a new season is upon us and that means I'm going to be actively
adding stuff for the next few weeks.

I just push the updated titles to prepare for this.

If anyone has any pulls or additions that they would like me to add now is the
time to refactor them against the current head.  I will probably pushing my
commits around 00:00 UTC most days.  I will try to check both the pull and
issue reqs when I start working on this stuff around 20:00-22:00 UTC.

Pulls should be against current master.  All edits should be done on
anime-list-master.xml, remember to set the default season ( this still bites me
occasionally ).  If all you can do is make a request then pleas generate and
upload a unified diff.  I don't have much free time to actually be doing this.

I do understand everyone's frustration with the lack of activity here, but
remember that I am just a casual user like the rest, with some unasked for
privileges that I didn't ask for.

I will do what I can and I will try to give feedback also.

I am planing to start doing my pushes on Tuesday, July 2, since that's when my
first show of summer 2019 starts.

**Comment by purposelycryptic** [comment]
@slohj 

Ok, so, as per my last commit comment, there are a handful of conflicts between the master and my branch, due to some changes in TheTVDB requiring edited values, and also one typo, due to which there has been a whole lot of duplicate work going on - I've collected the edits below for easy review. Everything else should be fine, since I just spent several hours manually comparing/merging the two in NP++ before committing. 

Note, this PR has all the changes from @atraholt 's Pull Request #239 , as I implemented it on my branch a long time ago.

## Edits:

```xml
  <anime anidbid="2430" tvdbid="81115" defaulttvdbseason="1" episodeoffset="" tmdbid="" imdbid="">
    <name>Mahou Shoujo Lyrical Nanoha</name>			   
  </anime>
```
  
  **becomes**
  
```xml
  <anime anidbid="2430" tvdbid="81115" defaulttvdbseason="1" episodeoffset="" tmdbid="" imdbid="tt0808082">
    <name>Mahou Shoujo Lyrical Nanoha</name>
    <mapping-list>
      <mapping anidbseason="0" tvdbseason="0">;1-99;2-99;3-99;4-99;5-99;6-99;7-99;8-99;9-99;</mapping>
    </mapping-list>
  </anime>
```
This maps specials that don't exist on TheTVDB to S0E99 - again, based on the PR by @atraholt, modified since someone decided to actually map an episode on TheTVDB to S0E00 (which the original PR mapped these episodes to), so, as per the readme, to S0E99 they go:
nanohaspecadb
nanohaspectvdb




```xml
  <anime anidbid="8517" tvdbid="142601" defaulttvdbseason="0" episodeoffset="8" tmdbid="" imdbid="">
    <name>Kidou Senshi Gundam: The Origin</name>
  </anime>
```
  
  **becomes**
  
```xml
  <anime anidbid="8517" tvdbid="142601" defaulttvdbseason="0" episodeoffset="" tmdbid="" imdbid="">
    <name>Kidou Senshi Gundam: The Origin</name>
  </anime>
```
The offset was removed:
gundamADB
gundamTVDB




```xml
  <anime anidbid="9788" tvdbid="81115" defaulttvdbseason="0" episodeoffset="" tmdbid="" imdbid="">
    <name>Magical Girl Lyrical Nanoha Reflection</name>
    <mapping-list>
      <mapping anidbseason="1" tvdbseason="0">;1-12;</mapping>
    </mapping-list>
  </anime>
```
  
  **becomes**
  
```xml
  <anime anidbid="9788" tvdbid="81115" defaulttvdbseason="0" episodeoffset="" tmdbid="" imdbid="">
    <name>Magical Girl Lyrical Nanoha Reflection</name>
    <mapping-list>
      <mapping anidbseason="1" tvdbseason="0">;1-16;</mapping>
    </mapping-list>
  </anime>
```
Reflection was changed to S0E16 on TheTVDB at some point - this also came from atraholt's PR:
nanohatvdb




## Typo:

```xml
  <anime anidbid="9826" tvdbid="267440" defaulttvdbseason="0" episodeoffset="" tmdbid="" imdbid="">
    <name>Shingeki no Kyojin OAD</name>
    <mapping-list>
      <mapping anidbseason="1" tvdbseason="0">;1-2;2-12;3-13;4-16;5-17;6-20;7-21;8-22</mapping>
    </mapping-list>
  </anime>
```
  
  **becomes**
  
```xml
  <anime anidbid="9826" tvdbid="267440" defaulttvdbseason="0" episodeoffset="" tmdbid="" imdbid="">
    <name>Shingeki no Kyojin OAD</name>
    <mapping-list>
      <mapping anidbseason="1" tvdbseason="0">;1-2;2-12;3-13;4-16;5-17;6-20;7-21;8-22;</mapping>
    </mapping-list>
  </anime>
```
Missing Semi-Colon at the end of the mapping in the master.

Hopefully implementing these edits will allow the merge to finally go through, as quite few additions have built up over the months. 

Thanks for giving me hope this Repo may yet keep going, and sorry for being late to the party; while I finally got my test results and am ecstatic that I don't have Cancer, I'm still quite ill and have my lungs slowly trying to kill themselves, with only educated guesses as to why (along with fun guess-treatments). It's kind of seriously messed up my ability to work on any kind of schedule. But I'm not dying! ...I think. Hopefully. Not of cancer, anyway. Which is a good thing :)

**Pull request closed without merging**
